### ISSUE TITLE
fixed file helpers

### ISSUE THREAD

**Issue by FrankReh** [tokio-rs/io-uring#178]
This crate doesn't call them helpers but the liburing does and for this, that seems reasonable too.

`io-uring` is missing helper support for direct files in its operations that can accept them.

- [x] openat_direct (being worked by #181)
- [x] openat2_direct (also being worked by #181)
- [x] close_direct (also being worked by #181)
- [x] socket_direct (edit: handled by opcode::Socket with builder method file_index() #179)
- [x] accept_direct (being worked by #184)
- [x] multishot_accept_direct (being worked by #186)

What kind of naming convention would be acceptable for the new class of helper and can they take an enum that represents either a fixed slot number to use or the AUTO choice of the device itself?

**Comment by lucab** [comment]
>  * socket_direct

I started having a look at implementing `IORING_OP_SOCKET`.
I'm slightly puzzled by the `_direct` helpers in liburing, because some of them see to concern **input** FDs (e.g. `close`), while some of them concern **output** FDs (e.g. `openat`).

Maybe the `socket` opcode is an outlier here as it is only concerned with output FDs.
I'm not sure it even needs a dedicated direct helper. Instead a unified helper can be modeled this way:
```rust
opcode!(
    pub struct Socket {
        domain: { i32 },
        socket_type: { i32 },
        protocol: { i32 },
        ;;
        destination_slot: Option<types::DestinationSlot> = None,
    })
```

**Comment by FrankReh** [comment]
@lucab Nice. I agree the signature you are proposing looks like it obviates the need for additional opcodes.

The liburing close_direct is an odd-ball. Yes, it is an input argument and in other cases they use a single bit to indicate the input fd is a fixed slot. But the command is actually doing two things in the device, it is calling close on the file *and* it is unregistering the descriptor from the fixed table.

**Comment by FrankReh** [comment]
Thanks @lucab. Once you got support in for `opcode::Socket` the rest were easy to make follow suite.

**Comment by lucab** [comment]
@FrankReh thank you for your patches!
